### ISSUE TITLE
Would you please add a gem for this library? #FeatureRequest

### ISSUE THREAD

**Issue by siuying** [clayallsopp/Routable#1]
Thank you for this cool library! 

It would be a lot easier to use if it is a gem. Detailed in [Create Gems for RubyMotion](http://reality.hk/posts/2012/05/22/create-gems-for-rubymotion/).

**Comment by clayallsopp** [comment]
Just finished with 123e444f71d6f2506db37041409a7f650a9cc01a. `gem install routable` should work now

**Comment by siuying** [comment]
Thank you!
